call plug#begin()
Plug 'itchyny/lightline.vim'
Plug 'ghifarit53/tokyonight-vim'
Plug 'rbtnn/vim-ambiwidth'
Plug 'sheerun/vim-polyglot'
Plug 'lambdalisue/vim-fern'
Plug 'lambdalisue/vim-nerdfont'
Plug 'lambdalisue/vim-glyph-palette'
Plug 'lambdalisue/vim-fern-renderer-nerdfont'
call plug#end()

set encoding=utf-8
set fileencodings=iso-2022-jp,iso-2022-jp-2,utf-8,euc-jp,sjis

set nocompatible
set number
set relativenumber
set noerrorbells
set visualbell
set viminfo=
set list
set listchars=tab:»-,trail:-,eol:↲,extends:»,precedes:«,nbsp:%
set wrap
set display=lastline
set pumheight=10
set tabstop=4
set autoindent
set expandtab
set shiftwidth=4
set smartindent
set whichwrap=b,s,[,],<,>
set backspace=indent,eol,start
set ambiwidth=single
set clipboard+=unnamed

syntax enable

if !has('gui_running')
  set t_Co=256
endif

" theme
set termguicolors
let g:tokyonight_style = 'night' " available: night, storm
let g:tokyonight_transparent_background = 1
colorscheme tokyonight

" lightline
set noshowmode
set laststatus=2
let g:lightline = {
      \ 'colorscheme': 'tokyonight',
      \ }

" fern
nnoremap <C-n> :Fern . -reveal=% -drawer -toggle -width=40<CR>
augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
augroup END
let g:fern#renderer = "nerdfont"
