[env]
TERM = "xterm-256color"
[window]
opacity = 0.9
[font]
size = 14
[font.normal]
family = "PlemolJP Console NF"
[font.bold]
family = "PlemolJP Console NF"
style = "Bold"
[font.italic]
family = "PlemolJP Console NF"
style = "Italic"
[font.bold_italic]
family = "PlemolJP Console NF"
style = "Bold Italic"

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]
