[env]
TERM = "xterm-256color"
[window]
opacity = 0.9
[font]
size = 16
[font.normal]
family = "Cica"
[font.bold]
family = "Cica"
style = "Bold"
[font.italic]
family = "Cica"
style = "Italic"
[font.bold_italic]
family = "Cica"
style = "Bold Italic"

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]
